name: $bog_talks

permissions: write-all

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: hyoo-ru/mam_build@master2
        with:
          package: "bog/talks"

      - uses: hyoo-ru/gh-deploy@v4.4.1
        if: github.ref == 'refs/heads/main'
        with:
          folder: "bog/talks/-"
